### ISSUE TITLE
about the param "xyzstoframes"

### ISSUE THREAD

**Issue by flyingshan** [USTC3DV/NeRFBlendShape-code#11]
I am curious about the parameter "xyzstoframes" used in the code, where it seems not used in inference. I wonder what is the param for. Thank you!

**Comment by XuanGhahahaha** [comment]
Hi! This variable is not used in inference. 

In original torch-ngp implementation, they only consider a static scene. So only one hash table needs to be queried. But in our case, different frames correspond to different hash tables. There will be _batchsize_ hash tables to queried in every optimization iteration.

When training with _batchsize_>1, because  different frames occupy different number of sample points (due to the empty-skip strategy of instant-ngp). This 'xyzstoframes' could be used to indentify which hash table the sample point need to be queried in.

But in inference code, because we simply set _batchsize_=1, all the sampled points belong to one hash table corresponding to current frame. So we could just set this variable to 0 for convenience.

**Comment by flyingshan** [comment]
Thank you, got it!
