### ISSUE TITLE
question about the ExpHashEncoder implementation

### ISSUE THREAD

**Issue by 07hyx06** [USTC3DV/NeRFBlendShape-code#12]
Hi, thanks for solid your work and code! 

I wonder why not directly use the hash encoder provided in the `tinycudann` lib in the implementation? Are there some special concerns? Is the hash encoder provided by the `tinycudann` lib not compatible with the cuda accelerated ray marching?

Thanks!

**Comment by XuanGhahahaha** [comment]
Hi, that's because in _instant-ngp_ algorithm, the sample points only need to be queried in one hash table. But in our training, in every iteration, there will be _batch_size_ different hash tables(combined by our implicit blendshapes) to be queried in. And due to the empty-skip ray marching, the number of sample points queried in each hash table will be different. So we choose to use this _ExpHashEncoder_ but not _tiny-cuda-nn_ version for convenience.
