### ISSUE TITLE
Advice on generating own tracking data

### ISSUE THREAD

**Issue by Kartik-Teotia** [USTC3DV/NeRFBlendShape-code#18]
Hi, 

First of all, amazing work!

I had questions about what are max_per and min_per doing in the code and how can we calulate them? And are expression coefficients the same as expression parameters obtained from a 3DMM model? I basically want to know how this combination is taking place and how can I generate my own data for it using a 3DMM tracker.

Thanks

**Comment by XuanGhahahaha** [comment]
Hi,

Thanks for your interest in our work.

_max_per_ and _min_per_  means element-wise maximum/minimum of our expression coefficients in train set. These variables are used to restrict the range of expression coefficients when inference, which could avoid the bad results when test expression is far from the train set distribution. They are also used for our _expression-aware density grid update_ operation.

Because 3DMM model is a PCA model, which lacks semantic meaning for every basis, the expression coefficients here are not tracked with a 3DMM model, but with a blendshape model. In our experiments, we use the blendshape of [FaceWarehouse](https://www.google.com.hk/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&ved=2ahUKEwjkzruouYf9AhUEs1YBHXAiDs8QFnoECBUQAQ&url=http%3A%2F%2Fkunzhou.net%2Fzjugaps%2Ffacewarehouse%2F&usg=AOvVaw3sAB8OCPTPrqLCcbB1E_Lm) for tracking.

**Comment by Kartik-Teotia** [comment]
Ah, is the blendshape coefficient-based tracking not available for public use?

**Comment by XuanGhahahaha** [comment]
It is not available here, that's because the tracking code is occupied by the Image Derivative Inc., which I unfortunately don't have right to make it public.

**Comment by Kartik-Teotia** [comment]
Do you think the method can work with PCA coefficients instead?

**Comment by XuanGhahahaha** [comment]
Hi, on theory, it should also work with PCA coefficients.

**Comment by cucdengjunli** [comment]
> It is not available here, that's because the tracking code is occupied by the Image Derivative Inc., which I unfortunately don't have right to make it public.

I try to re produce it

**Comment by Ling27** [comment]
@cucdengjunli Have you been able to reproduce the tracking? Thank you!

**Comment by ZXisSpider** [comment]
> @cucdengjunli Have you been able to reproduce the tracking? Thank you!

Have you tried using Deep3Dface as tracking to reproduce the results?
