### ISSUE TITLE
New expression

### ISSUE THREAD

**Issue by pranavmalikk** [USTC3DV/NeRFBlendShape-code#3]
When you input a new expression does the model have to be re-trained everytime? I see that you concatenate the queried feature with the expression code so it seems like every time there's a new expression code we have to train the model again. How is inference handled in this model? Very nice paper btw with what looks like great results!

**Comment by XuanGhahahaha** [comment]
Hi, thanks for your interest.

Our model needs subject-specific training. But when a model trained, you could use anyone's facial expression coefficients to linearly combine the hash tables. If you have trained a model of a subject A on A's RGB sequence, you could use a different subject B's facial expression to combine A's bases for inference because the expression coefficients share the same space. No extra training is needed during inference.
