### ISSUE TITLE
What is exp_ori in the given dataset?

### ISSUE THREAD

**Issue by ChikaYan** [USTC3DV/NeRFBlendShape-code#32]
Hi,

Thank you so much for the excellent code and for at least making the inference code avaliable!

May I ask a quick question -- in the released dataset there seems to be a `exp_ori`, which is passed all the way to the `forward()`, but is actually not used (only `exp` is used). May I ask what exactly is `exp_ori`?

Many thanks!

**Comment by XuanGhahahaha** [comment]
Hi, thanks for your interest in our work.

Only `exp_ori` is used in our implementation. You could see the following reference to  verify this:
https://github.com/USTC3DV/NeRFBlendShape-code/blob/d198ac270b9994e36d7ef86003777a2c1976ca7a/nerf/provider.py#L131C46-L131C53

`exp_ori` is 46-dim, which represents the extent of blendshape's 46 AU activations. But in some video, not every AU could activated, so `exp` is a subset of `exp_ori` that could be actually activated in one video. 

Selecting a subset is not necessary, so you could ignore `exp` because it is not used in this code anymore.

**Comment by ChikaYan** [comment]
Ah I see, thanks a lot for the detailed explaination!
